workflows:
  android-workflow:
    name: Android Release Build
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      android_signing:
        - keystore_reference
      vars:
        FLUTTER_BUILD_ARGS: "--release --flavor production"

    triggering:
      branch_patterns:
        - pattern: master
          include: true

    scripts:
      - name: Get Flutter dependencies
        script: flutter pub get

      - name: Build Android App
        script: flutter build appbundle $FLUTTER_BUILD_ARGS

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
      - build/app/outputs/bundle/release/app-release.aab

  ios-workflow:
    name: iOS Release Build
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      ios_signing:
        distribution_type: development   # or ad_hoc / app_store
        bundle_identifier: com.example.app

    scripts:
      - name: Get Flutter dependencies
        script: flutter pub get

      - name: Build iOS
        script: flutter build ipa --release --flavor production

    artifacts:
      - build/ios/ipa/*.ipa
